kind: pipeline
name: default
steps:
  - name: hello
    image: alpine
    commands:
      - echo "Hi form the first step"
  - name: build-image
    image: plugins/docker
    settings:
      repo: fagoner/gitintro
      username:
        from_secret: docker_username
      password:
        from_secret: docker_pass
